package entity;
// Generated 6 f�vr. 2016 21:43:55 by Hibernate Tools 3.6.0

import hibernate.DAO;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * ConfigUcs generated by hbm2java
 */
@Entity
@Table(name = "config_barcode")
public class ConfigBarcode extends DAO implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "config_barcode_id_seq")
    @SequenceGenerator(name = "config_barcode_id_seq", sequenceName = "config_barcode_id_seq", allocationSize = 1)
    private Integer id;
    
    /*keyword to select a type of barcode_pattern in the code */
    @Column(name = "key_word")
    private String keyWord;
    
    @Column(name = "description")
    private String description;
    
    @Column(name = "barcode_pattern")
    private String barcodePattern;
    
    @Column(name = "harness_part")
    private String harnessPart;
    
    @Column(name = "customer")
    private String customer;
    

    @ManyToOne(optional = true, cascade = CascadeType.REFRESH)
    private ConfigUcs ucs;
    
     public ConfigBarcode() {}

    public ConfigBarcode(String keyWord, String description, String barcodePattern, String harnessPart, String customer) {        
        this.keyWord = keyWord;
        this.description = description;
        this.barcodePattern = barcodePattern;
        this.harnessPart = harnessPart;
        this.customer = customer;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getReference() {
        return keyWord;
    }

    public void setReference(String keyWord) {
        this.keyWord = keyWord;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getBarcodePattern() {
        return barcodePattern;
    }

    public void setBarcodePattern(String barcodePattern) {
        this.barcodePattern = barcodePattern;
    }

    public ConfigUcs getConfigUcs() {
    return ucs;
    }
    public void setConfigUcs(ConfigUcs ucs) {
    this.ucs = ucs;
    }
    public String getKeyWord() {
        return keyWord;
    }

    public void setKeyWord(String keyWord) {
        this.keyWord = keyWord;
    }

    public String getHarnessPart() {
        return harnessPart;
    }

    public void setHarnessPart(String harnessPart) {
        this.harnessPart = harnessPart;
    }

    public String getCustomer() {
        return customer;
    }

    public void setCustomer(String customer) {
        this.customer = customer;
    }
    
    
    
    
    
    
}
